/**
 *
 * $Id$
 */
package artifact.validation;

import artifact.ArtifactPackageInterface;

import base.ArtifactElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link artifact.ArtifactPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactPackageValidator {
	boolean validate();

	boolean validateArtifactElement(EList<ArtifactElement> value);
	boolean validateInterfaces(EList<ArtifactPackageInterface> value);
}
