/**
 *
 * $Id$
 */
package artifact.validation;

import artifact.ArtifactAsset;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link artifact.ArtifactAssetRelationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactAssetRelationshipValidator {
	boolean validate();

	boolean validateSource(EList<ArtifactAsset> value);
	boolean validateTarget(EList<ArtifactAsset> value);
}
