/**
 *
 * $Id$
 */
package digital_twin.validation;

import artifact.ArtifactPackage;

import component.ComponentPackage;

import digital_twin.DigitalTwinPackage;
import digital_twin.DigitalTwinPackageInterface;

import org.eclipse.emf.common.util.EList;

import terminology.TerminologyPackage;

/**
 * A sample validator interface for {@link digital_twin.DigitalTwinPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DigitalTwinPackageValidator {
	boolean validate();

	boolean validateDigitalTwinPackages(EList<DigitalTwinPackage> value);
	boolean validateInterfaces(EList<DigitalTwinPackageInterface> value);
	boolean validateComponentPackages(EList<ComponentPackage> value);
	boolean validateArtifactPackages(EList<ArtifactPackage> value);
	boolean validateTerminologyPackages(EList<TerminologyPackage> value);
}
