/**
 *
 * $Id$
 */
package base.validation;

import base.Coordinate;
import base.DTElement;
import base.Dimension;
import base.Heading;

/**
 * A sample validator interface for {@link base.DTElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DTElementValidator {
	boolean validate();

	boolean validateGid(String value);
	boolean validateIsCitation(boolean value);
	boolean validateIsAbstract(boolean value);
	boolean validateCitedElement(DTElement value);
	boolean validateCoordinate(Coordinate value);
	boolean validateDimension(Dimension value);
	boolean validateHeading(Heading value);
}
