/**
 *
 * $Id$
 */
package base.validation;

import base.ImplementationConstraint;
import base.LangString;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link base.ExternalReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExternalReferenceValidator {
	boolean validate();

	boolean validateLocation(LangString value);
	boolean validateType(LangString value);
	boolean validateMetadata(LangString value);
	boolean validateImplementationConstraint(EList<ImplementationConstraint> value);
}
