/**
 *
 * $Id$
 */
package base.validation;

import base.Description;
import base.ExternalReference;
import base.ImplementationConstraint;
import base.LangString;
import base.Note;
import base.TaggedValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link base.ModelElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelElementValidator {
	boolean validate();

	boolean validateName(LangString value);
	boolean validateDescription(Description value);
	boolean validateImplementationConstraint(EList<ImplementationConstraint> value);
	boolean validateNote(EList<Note> value);
	boolean validateTaggedValue(EList<TaggedValue> value);
	boolean validateExternalReference(ExternalReference value);
}
