/**
 *
 * $Id$
 */
package base.validation;

import base.MultiLangString;

/**
 * A sample validator interface for {@link base.TaggedValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaggedValueValidator {
	boolean validate();

	boolean validateKey(MultiLangString value);
}
