/**
 *
 * $Id$
 */
package component.validation;

import component.ComponentPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link component.ComponentPackageBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentPackageBindingValidator {
	boolean validate();

	boolean validateParticipantPackage(EList<ComponentPackage> value);
}
