/**
 *
 * $Id$
 */
package component.validation;

import component.ComponentElement;
import component.ComponentPackageInterface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link component.ComponentPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentPackageValidator {
	boolean validate();

	boolean validateComponents(EList<ComponentElement> value);
	boolean validateInterface(EList<ComponentPackageInterface> value);
}
