/**
 *
 * $Id$
 */
package component.validation;

import base.ArtifactElement;

import component.FailureSeverity;
import component.FinalEffect;
import component.HigherLevelEffect;
import component.RegionalEffect;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link component.FailureMode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FailureModeValidator {
	boolean validate();

	boolean validateMode(String value);
	boolean validateCause(String value);
	boolean validateProbability(float value);
	boolean validateSafety_related(boolean value);
	boolean validateFailureSeverity(FailureSeverity value);
	boolean validateHazards(EList<ArtifactElement> value);
	boolean validateRegional(RegionalEffect value);
	boolean validateHigher_level(HigherLevelEffect value);
	boolean validateFinal(FinalEffect value);
}
