/**
 *
 * $Id$
 */
package component.validation;

import component.Cost;
import component.FailureMode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link component.SafetyMechanism}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SafetyMechanismValidator {
	boolean validate();

	boolean validateHandle(FailureMode value);
	boolean validateMechanism(String value);
	boolean validateCoverage(float value);
	boolean validateCosts(EList<Cost> value);
}
