/**
 *
 * $Id$
 */
package terminology.validation;

import org.eclipse.emf.common.util.EList;

import terminology.Category;

/**
 * A sample validator interface for {@link terminology.ExpressionElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionElementValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateCategory(EList<Category> value);
}
