/**
 *
 * $Id$
 */
package terminology.validation;

import org.eclipse.emf.common.util.EList;

import terminology.ExpressionElement;

/**
 * A sample validator interface for {@link terminology.Expression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionValidator {
	boolean validate();

	boolean validateElement(EList<ExpressionElement> value);
}
